"""Authoritative state vocabulary for SIH 2026 PS 26228.

Authority: ``docs/TECHNICAL_SPECIFICATION.md`` §§3.2, 3.14, 4.4, 8.9,
and ``docs/sp003_vocabulary_contract.md``.
"""


class AssessmentStatus:
    """Values permitted in a worker output's ``assessment_status`` field."""

    COMPLETED = "COMPLETED"
    ASSESSMENT_ERROR = "ASSESSMENT_ERROR"
    UNAVAILABLE = "UNAVAILABLE"
    UNSUPPORTED = "UNSUPPORTED"
    DEFERRED_IN_SCOPE = "DEFERRED_IN_SCOPE"
    ARTIFACT_UNIT_AMBIGUOUS = "ARTIFACT_UNIT_AMBIGUOUS"
    LOAD_BLOCKED = "LOAD_BLOCKED"
    LOAD_SUCCESS = "LOAD_SUCCESS"
    LOAD_ERROR = "LOAD_ERROR"
    ONNX_PATH_CONTAINMENT_VIOLATION = "ONNX_PATH_CONTAINMENT_VIOLATION"
    STRUCTURAL_VALID = "STRUCTURAL_VALID"
    STRUCTURAL_INVALID = "STRUCTURAL_INVALID"
    REFERENCE_UNAVAILABLE = "REFERENCE_UNAVAILABLE"


class SupervisorOutcome:
    """Supervisor outcome that is not a persisted worker assessment status."""

    SCHEMA_VIOLATION = "SCHEMA_VIOLATION"


class DetectionStatus:
    UNAVAILABLE = "UNAVAILABLE"
    ANOMALY_DETECTED = "ANOMALY_DETECTED"
    IDENTITY_MATCH = "IDENTITY_MATCH"
    IDENTITY_DIFFERENT = "IDENTITY_DIFFERENT"
    NO_ANOMALY_DETECTED = "NO_ANOMALY_DETECTED"
    COMPLETED_STATISTICS_ONLY = "COMPLETED_STATISTICS_ONLY"
    DEFERRED_IN_SCOPE = "DEFERRED_IN_SCOPE"


class InterpretationStatus:
    UNAVAILABLE = "UNAVAILABLE"
    REQUIRES_INVESTIGATION = "REQUIRES_INVESTIGATION"
    CONSISTENT_WITH_EXPECTED = "CONSISTENT_WITH_EXPECTED"
    IDENTITY_DEVIATION_DETECTED = "IDENTITY_DEVIATION_DETECTED"
    STATISTICS_REPORTED = "STATISTICS_REPORTED"
    NO_ANOMALY_DETECTED = "NO_ANOMALY_DETECTED"
    DEFERRED = "DEFERRED"


class AnalystDisposition:
    ACCEPT = "ACCEPT"
    ACCEPT_WITH_CONTEXT = "ACCEPT_WITH_CONTEXT"
    ESCALATE = "ESCALATE"
    CONTAIN_HOLD = "CONTAIN_HOLD"
    OVERRIDE = "OVERRIDE"
    UNAVAILABLE_NO_DECISION = "UNAVAILABLE_NO_DECISION"


class IdentityQuality:
    TRUSTED = "TRUSTED"
    UNTRUSTED = "UNTRUSTED"
    UNAVAILABLE = "UNAVAILABLE"


class ReferenceHealth:
    HEALTH_VERIFIED = "HEALTH_VERIFIED"
    HEALTH_UNVERIFIED = "HEALTH_UNVERIFIED"
    FORMAT_ASSET = "FORMAT_ASSET"
    CONTAMINATION_SUSPECTED = "CONTAMINATION_SUSPECTED"
    STALE_SUSPECTED = "STALE_SUSPECTED"
    UNAVAILABLE = "UNAVAILABLE"


class ApplicabilityStatus:
    APPLICABLE = "APPLICABLE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNSUPPORTED = "UNSUPPORTED"
    DEFERRED_IN_SCOPE = "DEFERRED_IN_SCOPE"
    REFERENCE_UNAVAILABLE = "REFERENCE_UNAVAILABLE"


class AccessMode:
    BLACK_BOX = "BLACK_BOX"
    GREY_BOX = "GREY_BOX"
    WHITE_BOX = "WHITE_BOX"
    INTERNAL_ACTIVATION = "INTERNAL_ACTIVATION"
    UNAVAILABLE = "UNAVAILABLE"


class SigningStatus:
    SIGNED = "SIGNED"
    SIGNING_UNAVAILABLE = "SIGNING_UNAVAILABLE"


class SignatureAlgorithm:
    HMAC_SHA256 = "HMAC-SHA256"


class AuditEventType:
    PIPELINE_RUN_START = "PIPELINE_RUN_START"
    PIPELINE_RUN_COMPLETE = "PIPELINE_RUN_COMPLETE"
    PIPELINE_RUN_ERROR = "PIPELINE_RUN_ERROR"
    WORKER_DISPATCHED = "WORKER_DISPATCHED"
    WORKER_RESULT_ACCEPTED = "WORKER_RESULT_ACCEPTED"
    WORKER_RESULT_REJECTED_SCHEMA_VIOLATION = (
        "WORKER_RESULT_REJECTED_SCHEMA_VIOLATION"
    )
    EVIDENCE_RECORD_WRITTEN = "EVIDENCE_RECORD_WRITTEN"
    FINDING_WRITTEN = "FINDING_WRITTEN"
    PROVENANCE_RECORD_WRITTEN = "PROVENANCE_RECORD_WRITTEN"
    DEFERRED_IN_SCOPE_EMITTED = "DEFERRED_IN_SCOPE_EMITTED"
    REFERENCE_HEALTH_TRANSITION = "REFERENCE_HEALTH_TRANSITION"
    SIGNING_UNAVAILABLE = "SIGNING_UNAVAILABLE"
    SEQUENCE_GAP_DETECTED = "SEQUENCE_GAP_DETECTED"
    CHAIN_CORRUPT = "CHAIN_CORRUPT"
    ANALYST_DISPOSITION = "ANALYST_DISPOSITION"
    CAPABILITY_DECLARATION_EMITTED = "CAPABILITY_DECLARATION_EMITTED"
    UNAVAILABLE_PROPAGATED = "UNAVAILABLE_PROPAGATED"
    REPLAY_ATTEMPT_DETECTED = "REPLAY_ATTEMPT_DETECTED"


PF_002_NON_CLAIM = (
    "Cryptographic signature establishes that this record was produced and not modified "
    "after signing under accepted-key assumptions. It does NOT establish: "
    "(a) that the named model executed the assessed inferences (PF-002); "
    "(b) that the assessment was accurate; "
    "(c) that the signing key was not compromised; or "
    "(d) that the system producing this record was not itself compromised."
)

FIELD_COVERAGE_GAP_CLEAN_LABEL = "coverage_gap_clean_label"
FIELD_ANOMALY_NOT_MALICIOUS_NON_CLAIM = "anomaly_not_malicious_non_claim"
FIELD_GLOBAL_BACKDOOR_ABSENCE_NOT_ESTABLISHED = (
    "global_backdoor_absence_not_established"
)
FIELD_PF_002_NON_CLAIM = "pf_002_non_claim"

GENESIS_HASH = "GENESIS"
DEFAULT_ANALYST_ID = "UNAVAILABLE"  # OQ-017: authentication not established.
SIGNING_ALGORITHM_PENDING = "PENDING_XREG_002"
CANONICALIZATION_ALGORITHM_ID = "json-canonical-utf8-sort-keys-v1"
